language: ruby
sudo: false
rvm:
  - 2.3.0
services:
  - postgresql
script:
  - bundle install
  - RAILS_ENV=test bin/rails db:create
  - RAILS_ENV=test bin/rails db:migrate
  - bin/rails test
before_script:
  - psql -c 'create database dripcoffee_rugbyboard_test;' -U postgres
  - cp config/secrets.travis.yml config/secrets.yml
notifications:
  email: false
  slack: navyblue-team:ioO5diAGc5WUQVDKc5BH1UbE
