# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15c9a991f9e08953e0b5d1561ddf3b1d0be9dcae58731d1967fd0dae76e0e0e089b4b42c0e10765b196da2c8a547fcebd07031120a298d02a66be3b716ccd605

test:
  secret_key_base: c66535b3365ed3ddffe05e7405b3d368cabf508bdac6b358c67d02954d5d6f22014505110cb459afe103303b8541c5b7d9c25c95d7bcf4d5614b49093b8629eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
